  services:
    postgres_games_db:
      image: 'postgres:16.1-alpine'
      restart: always
      environment:
        - 'POSTGRES_DB=gameplatform'
        - 'POSTGRES_USER=game_admin'
        - 'POSTGRES_PASSWORD=game_admin_password'
      ports:
        - '5440:5432'
      networks:
        - backend
      volumes:
        - ./postgres/data:/var/lib/postgres

    postgres_checkers_db:
      image: 'postgres:16.1-alpine'
      restart: always
      environment:
        - 'POSTGRES_DB=checkers'
        - 'POSTGRES_USER=game_admin'
        - 'POSTGRES_PASSWORD=game_admin_password'
      ports:
        - '5441:5432'
      networks:
        - backend
      volumes:
        - ./postgres/data:/var/lib/postgres


    postgers_test_db:
      image: 'postgres:16.1-alpine'
      restart: always
      environment:
        - 'POSTGRES_DB=test-db'
        - 'POSTGRES_USER=user'
        - 'POSTGRES_PASSWORD=password'
      ports:
        - '5442:5432'
      networks:
        - backend
      volumes:
        - ./postgres/data:/var/lib/postgres

    app_rabbitmq:
      image: rabbitmq:3.13.7-management-alpine
      environment:
        - RABBITMQ_DEFAULT_USER=game_user
        - RABBITMQ_DEFAULT_PASS=game_user_password
      ports:
        - "5672:5672" #AMQP
        - "15672:15672" #MGMT
      networks:
        - backend
      volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq/

    idp_postgres:
      image: postgres:15.4
      volumes:
        - ./postgres/data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - '5433:5432'
      networks:
        - kc


    idp_keycloak:
      image: quay.io/keycloak/keycloak:25.0.5
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=postgres
        - KC_DB_URL_HOST=idp_postgres
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=password
      command: start-dev --import-realm
      volumes:
        - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      ports:
        - "8180:8080"
      depends_on:
        - idp_postgres
      networks:
        - kc


  networks:
    kc:
      driver: bridge
    backend:
      driver: bridge


